# -*- coding: utf-8 -*-

{
    'name': 'Supplier fee',
    'version': '0.1',
    'category': 'Accounting',
    'description': """Add fee line for each supplier invoice generated by reception.""",
    'author': 'Elneo',
    'website': 'http://www.elneo.com',
    'depends': ['base','purchase','account'],
    "data" : ['views/supplier_fee_view.xml'],
    'installable': True,
    'auto_install': False,
    'application': True,
}
