# -*- coding: utf-8 -*-
##############################################################################
#
#    Elneo
#    Copyright (C) 2011-2015 Elneo (Technofluid SA) (<http://www.elneo.com>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
from datetime import datetime

from openerp import fields, models, api, _
from openerp.exceptions import Warning



class InterventionMerge(models.TransientModel):
    _inherit='maintenance.intervention.merge.wizard'
    
    @api.model
    def _get_interventions(self):
        
        # WE LOOK FOR INTERVENTIONS THAT ARE IN DIFFERENT PROJECTS AND RAISE WARNING
        interventions = super(InterventionMerge,self)._get_interventions()

        projects = interventions.mapped('project_id')

        
        if len(projects) > 1 :
            raise Warning(_('You cannot merge interventions that were generated by different projects! Please select interventions on the same project.'))
        
            
        return interventions
    
    intervention_lines = fields.Many2many(default=_get_interventions)
    
    
